# Generated by Django 5.2.8 on 2025-12-15 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userconnection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='requester',
        ),
        migrations.AlterModelOptions(
            name='letterversion',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='letterversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='letterversion',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='letterversion',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ModificationRequest',
        ),
        migrations.DeleteModel(
            name='UserConnection',
        ),
    ]
